
name: plot
channels:
  - conda-forge
  - defaults
dependencies:
aiohttp==3.6.2
arrow==0.15.5
asciinema==2.0.2
asn1crypto==1.3.0
astroid==1.5.3
async-timeout==3.0.1
attrs==19.3.0
Automat==20.2.0
beautifulsoup4==4.4.1
bleach==3.1.0
boto==2.44.0
Brlapi==0.6.7
cachetools==4.0.0
certifi==2017.4.17
cffi==1.14.0
chardet==3.0.3
Click==7.0
click-plugins==1.1.1
colorama==0.3.9
config==0.4.2
ConfigArgParse==1.0
constantly==15.1.0
construct==2.10.56
coursera-dl==0.11.5
cryptography==2.8
cssselect==1.1.0
cssutils==1.0.2
cupshelpers==1.0
cycler==0.10.0
Cython==0.29.2
decorator==4.4.1
defusedxml==0.5.0
discord==1.0.1
discord.py==1.3.2
distro==1.4.0
distro-info==0.21
dnspython==1.15.0
entrypoints==0.3
enum34==1.1.6
future==0.16.0
google==2.0.3
greenlet==0.4.15
html5lib==1.0.1
httplib2==0.17.0
hyperlink==19.0.0
idna==2.5
incremental==17.5.0
ipydatawidgets==4.0.1
ipykernel==4.9.0
ipython==5.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
iso-639==0.4.5
iso639==0.1.4
isort==4.2.14
jedi==0.16.0
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
keyring==17.1.1
keyrings.alt==3.1.1
kiwisolver==1.1.0
lazy-object-proxy==1.3.1
louis==3.8.0
lxml==4.5.0
Mako==1.0.7
MarkupSafe==1.1.0
matplotlib==3.2.0
mccabe==0.6.1
mistune==0.8.4
mpmath==1.1.0
msgpack==0.5.6
multidict==4.7.5
mysqlclient==1.3.10
nbconvert==5.4.0
nbformat==4.4.0
neovim==0.3.0
nose==1.3.7
notebook==5.7.8
numpy==1.18.1
olefile==0.46
opencv-python==4.2.0.32
pandas==1.0.1
pandocfilters==1.4.2
parsel==1.5.2
parso==0.6.1
pefile==2019.4.18
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.4.1
pipenv==2018.11.26
prometheus-client==0.6.0
prompt-toolkit==1.0.15
Protego==0.1.16
protobuf==3.11.3
psutil==5.5.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycaption==1.0.1
pycountry==19.8.18
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.9.7
pycryptodomex==3.9.7
pycups==1.9.73
pycurl==7.43.0.2
PyDispatcher==2.0.5
Pygments==2.3.1
PyGObject==3.30.4
PyHamcrest==2.0.0
pyinotify==0.9.6
pylint==2.4.4
PyMonad==1.3
pynvim==0.4.1
pyOpenSSL==19.1.0
pyparsing==2.4.6
PySide2==5.14.1
PySimpleGUI==4.16.0
PySimpleSOAP==1.16.2
pysmbc==1.0.15.6
python-apt==1.8.4.1
python-dateutil==2.8.1
python-debian==0.1.35
python-debianbts==2.8.2
python-dotenv==0.9.1
python-pam==1.8.4
python-xapp==1.2.0
python-xlib==0.23
pythreejs==2.2.0
pytz==2019.3
pyxattr==0.6.1
pyxdg==0.25
pyzmq==17.1.2
queuelib==1.5.0
reportbug===7.5.3-deb10u1
reportlab==3.5.13
requests==2.21.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
scenedetect==0.5.1.1
scour==0.37
Scrapy==1.8.0
SecretStorage==2.3.1
selenium==3.141.0
Send2Trash==1.5.0
service-identity==18.1.0
setproctitle==1.1.10
shiboken2==5.14.1
shodan==1.21.3
simplegeneric==0.8.1
six==1.10.0
soupsieve==1.9.5
SQLAlchemy==1.3.13
sympy==1.5.1
tabview==1.4.4
terminado==0.8.1
testpath==0.4.2
tk==0.1.0
tornado==5.1.1
tqdm==4.43.0
traitlets==4.3.2
traittypes==0.2.1
Twisted==19.10.0
typed-ast==1.4.1
unattended-upgrades==0.1
urllib3==1.24.1
virtualenv==15.1.0
virtualenv-clone==0.5.3
w3lib==1.21.0
wcwidth==0.1.7
webencodings==0.5.1
websockets==8.1
widgetsnbextension==3.5.1
wrapt==1.10.10
XlsxWriter==1.2.8
xmltodict==0.12.0
yarl==1.4.2
youtube-dl==2020.2.16
zope.interface==4.7.1
